### ISSUE TITLE
In Fedora 21 io-usb fails to find libusb

### ISSUE THREAD

**Issue by xyz32** [nimious/libusb#1]
I am trying to run the list_devices_example.nim in Fedora 21 64bit, and after compiling successfully with nimble, when I try to run I get:

```
could not load: libusb.so
```

This is what I get from "dnf provides libusb":

```
Using metadata from Fri Mar 20 07:43:51 2015
libusb-1:0.1.5-5.fc21.x86_64 : A library which allows userspace access to USB devices
Repo        : @System

libusb-1:0.1.5-5.fc21.i686 : A library which allows userspace access to USB devices
Repo        : @System

libusb-1:0.1.5-5.fc21.i686 : A library which allows userspace access to USB devices
Repo        : fedora

libusb-1:0.1.5-5.fc21.x86_64 : A library which allows userspace access to USB devices
Repo        : fedora
```

And then "dnf install libusb" gives this:

```
Using metadata from Fri Mar 20 07:43:51 2015
Package libusb-1:0.1.5-5.fc21.x86_64 is already installed, skipping.
Package libusb-1:0.1.5-5.fc21.i686 is already installed, skipping.
Package libusb-1:0.1.5-5.fc21.x86_64 is already installed, skipping.
Package libusb-1:0.1.5-5.fc21.i686 is already installed, skipping.
Package libusb-1:0.1.5-5.fc21.x86_64 is already installed, skipping.
Package libusb-1:0.1.5-5.fc21.i686 is already installed, skipping.
Package libusb-1:0.1.5-5.fc21.x86_64 is already installed, skipping.
Package libusb-1:0.1.5-5.fc21.i686 is already installed, skipping.
Dependencies resolved.
Nothing to do.
```

**Comment by gmpreussner** [comment]
Sorry for the delay - I was super slammed. I have tested io-usb with **libusb 1.0.19** on ArchLinux. I can't help with Fedora right now, but will try Ubuntu as well. Could you try acquiring a newer version of the library?

**Comment by xyz32** [comment]
I solved it by changing 
`when defined(linux):
  const dllname = "libusb.so"`
to 
`when defined(linux):
const dllname = "libusb-1.0.so.0"`

Now this is a bit of a "hack" to make it work, I don't know how to solve it properly.

**Comment by gmpreussner** [comment]
Oh, I see. It looks like you're missing a symlink then. On Arch I have a symbolic link from _/usr/lib/libusb.so_ to _/installation/directory/libusb-x.x.so.x_  (whatever the currently installed version is).

If Fedora doesn't create this link for you, then you have to create it yourself. It is also possible that you already have the link somewhere, but it may not be in a location that is in the search path.

To create the link:

_sudo ln -s /installation/directory/libusb-1.0.so.0 /usr/lib/libusb.so_

I have never used Fedora, so please double check whether _/usr/lib_ is actually the library directory on that distribution.

**Comment by xyz32** [comment]
Annoying thing is that there are already 2 links in there:

```
lrwxrwxrwx   1 root root       19 Aug 17  2014 libusb-0.1.so.4 -> libusb-0.1.so.4.4.4
-rwxr-xr-x   1 root root    26512 Aug 17  2014 libusb-0.1.so.4.4.4
lrwxrwxrwx   1 root root       19 Aug 17  2014 libusb-1.0.so.0 -> libusb-1.0.so.0.1.0
-rwxr-xr-x   1 root root   102088 Aug 17  2014 libusb-1.0.so.0.1.0
```

I'll investigate a little more and I will open a issue with redhat if needed.

Thanks.

**Comment by gmpreussner** [comment]
Yes, this is normal. I have several links as well. It's a whole chain that includes more and more parts of the version number. Just add one for libusb.so that points to libusb-1.0.so.0

**Comment by gmpreussner** [comment]
Haven't heard from you in a while, so I assume you figured it out. Please reopen this issue if the problem persists. Thanks!

**Comment by xyz32** [comment]
Sorry I was in vacation.
Well it works if I do all the OS hacks, but if I distribute the software to someone else it will not work.
