### ISSUE TITLE
LibusbDeviceDescriptor

### ISSUE THREAD

**Issue by hohlerde** [nimious/libusb#3]
I was trying to build the list devices example under windows 64Bit with the latest Nim devel branch and vcc. I also used the latest libusb master branch. Everything compiled successfully but some product ids were printed as 0000. After changing the type cint to uint16 for idProduct and idVendor in LibusbDeviceDescriptor everything worked fine.

**Comment by gmpreussner** [comment]
Thanks, I'll take a look soon!

**Comment by gmpreussner** [comment]
Sorry for the delay - I've been too busy at work. Please let me know of any other issues in the future, thanks!
