### ISSUE TITLE
SIGSEGV with 32bit example binary on 64bit Windows 10

### ISSUE THREAD

**Issue by hohlerde** [nimious/libusb#4]
When compiling and running `list_devices_example.nim` as a 32bit binary using the 32bit libusb version 1.0.20 on a 64bit Win 10 I am getting a  SIGSEGV. When using libusb's default 32bit `listdevs.exe` everything seems fine.

However, when running `list_devices_example.nim` as a 64bit binary with the 64bit version of libusb on a 64bit Win 10 everything works fine, as well.

In order to run `list_devices_example.nim` as a 32bit binary on my 64bit Win 10 I did the following:
1. Downloading and installing http://nim-lang.org/download/nim-0.13.0_x32.exe (with Mingw and support dlls)
2. After installation `nim -v` shows the following: 
   
   Nim Compiler Version 0.13.0 (2016-01-19) [Windows: i386]
   Copyright (c) 2006-2015 by Andreas Rumpf
   
   git hash: a121c3f9eb2a348b9d6ae03ffd01aab26a238c30
   active boot switches: -d:release
3. Executing `nimble install io-usb`
4. Cloning https://github.com/nimious/libusb.git 
5. Downloading `libusb-1.0.20.7z` (windows binaries) from libusb.info
6. Extracting libusb-1.0.dll from MS32\dll folder of `libusb-1.0.20.7z` to example folder where `list_devices_example.nim` can be found
7. Going to example folder and running `nim c -d:release list_devices_example.nim`
8. Executing `list_devices_example.exe` gives the following output:

```
Success: Initialized libusb
Number of detected USB devices: 16
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

When compiling with default debug information by omiting `-d:release` I get all USB devices listed. Both, with 32 or 64bit version on a 64bit Win 10.

**Comment by Manuel83** [comment]
+1

**Comment by Manuel83** [comment]
Hi, 
Is there any update regarding this issue?

**Comment by gmpreussner** [comment]
I haven't had time yet, sorry. Please send me a pull request if you have a fix. Otherwise I'll try to check it out this weekend.

**Comment by netzadel** [comment]
+1 
any news?

**Comment by gmpreussner** [comment]
I'm not able to repro this. I am currently not set up to compile for 32-bit on Windows 10, so I had to compile on Windows 7. Here's what I did on a fresh machine:
1. Downloaded and installed http://nim-lang.org/download/nim-0.13.0_x32.exe with MinGW and Support DLLs
2. Cloned https://github.com/nimious/libusb.git
3. _nim c list_devices.example.nim_
4. Downloaded latest libusb binaries for Windows from http://libusb.info/
5. Copied _MS32\dll\libusb-1.0.dll_ into _list_devices_example.exe_ directory

**nim -v**

> Nim Compiler Version 0.13.0 (2016-01-19) [Windows: i386]
> Copyright (c) 2006-2015 by Andreas Rumpf
> git hash: a121c3f9eb2a348b9d6ae03ffd01aab26a238c30
> active boot switches: -d:release

**list_devices_example.exe**

> Success: Initialized libusb
> Number of detected USB devices: 11
> 8086:1D26 (bus 2, device 1)
> 8086:1D2D (bus 3, device 1)
> 104C:8241 (bus 1, device 1)
> 0424:2514 (bus 2, device 3) path: 1.5
> 0424:2640 (bus 2, device 7) path: 1.5.1
> 0424:4063 (bus 2, device 8) path: 1.5.1.1
> 045E:02D1 (bus 2, device 6) path: 1.8
> 046D:C24A (bus 2, device 4) path: 1.6
> 046D:C312 (bus 2, device 5) path: 1.7
> 8087:0024 (bus 3, device 2) path: 1
> 8087:0024 (bus 2, device 2) path: 1
> Exiting.

I then copied the compiled binaries from the Windows 7 machine to a Windows 10 machine and got comparable results there. So, the binaries compiled on Windows 7 work on a Windows 10 machine. Perhaps there is something wrong with the compiler on Windows 10, in which case it would be a question for the Nim developers.

**Comment by gmpreussner** [comment]
Nevermind, I read the original issue again and realized that the issue only appeared with _-d:release_. I was able to repro this on the Windows 7 machine.

**Comment by gmpreussner** [comment]
I haven't been able to figure this one out yet. The wrapper procs are all ok, but as soon as libusbInit() is invoked, the program will crash on shutdown. It also doesn't matter if libusb is initialized with or without a context. This may be a problem in the 32-bit binaries of libusb itself, but I'm not sure yet.

**Comment by gmpreussner** [comment]
We believe that this is a problem with the 32-bit library. Let's see if the next version fixes it.

**Comment by hohlerde** [comment]
Thanks a lot for your time investigating this, much appreciated. I will do some more research and try to go through the libusb code of the current version. If I find a solution I'll let you know. Hopefully the next libusb version works better.

**Comment by hohlerde** [comment]
Found the problem. I was using the libusb binary distribution for windows, where stdcall as calling convention is used. When changing cdecl to stdcall in the wrapper, everything works fine.
